name: release 
on:
  push:
    branches:
      - main
env:
  DOCKER_REPO: ghcr.io/coverwhale/micro-exporter
  REGISTRY: ghcr.io
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push images
        run: |
          docker build -t $DOCKER_REPO:${{github.sha}} -t $DOCKER_REPO:latest .
          docker push -a $DOCKER_REPO
