name: release
on:
  push:
    tags:
      - '*'
env:
  DOCKER_REPO: ghcr.io/CoverWhale/micro-exporter
permissions:
  id-token: write
  contents: read
jobs:
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with version and latest and push 
        run: |
          docker build -t $DOCKER_REPO:${{ github.ref_name }} -t $DOCKER_REPO:latest . 
          docker push -a $DOCKER_REPO
