name: tagged release
on:
  push:
    tags:
      - '*'
env:
  DOCKER_REPO: ghcr.io/coverwhale/micro-exporter
  REGISTRY: ghcr.io
permissions:
  id-token: write
  contents: read
jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: Log into registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: Build with version and latest and push 
        run: |
          docker build -t $DOCKER_REPO:${{ github.ref_name }} -t $DOCKER_REPO:latest . 
          docker push -a $DOCKER_REPO
